import csv
from web_scraper import scrape
from dotenv import load_dotenv
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_core.pydantic_v1 import BaseModel, Field
from langchain_openai import ChatOpenAI

from typing import List
import json
import os

load_dotenv()

class Contract(BaseModel):
    # Fields in a json object that we prompt AI what to find in terms of json
    # context: str = Field(default="", description="The contract's text.")
    # contract_date: str = Field(default="", description="The date the contract was issued.")
    company: str = Field(default="", description="The company that's named in the contract.")
    company_location: str = Field(default=[], description="The location of the company named in the contract.")
    awarded: int = Field(default=-1, description="The amount of funding the companies are awarded for the contract.")
    contract_reason: str = Field(default="", description="The reason the contract was awarded.")
    performance_location: str = Field(default="", description="The location in the format (City, State) where work will be performed in.")
    estimated_completion_date: str = Field(default="", description="The estimated completion date.")
    activity_group: str = Field(default="", description="The contracting activity group.")
    activity_group_location: str = Field(default="", description="The location of the contracting activity group.")
    activity_code: str = Field(default="", description="The contracting activity code.")
    contract_type: str = Field(default="", description="The type of contract the funding falls under.")
    is_modification: bool = Field(default=False, description="Whether this is a modification to a previous contract.")
    # agency: str = Field(default="", description="The federal agency that is responsible for the contract.")

class Article(BaseModel):
    contracts: List[Contract] = Field(default="", description="A list where each item has the information for a contract summary.")

# def get_format_instructions(parser) -> str:
#     instructions = f"""{parser.get_format_instructions()}
#     Note: JSON output must be constructed with double-quotes. Double quotes and Single quotes within strings must be escaped with a backslash.
#     """
#     return instructions

# contract_text = """
# ARMY

# DRS Network & Imaging Systems LLC, Melbourne, Florida, was awarded a $177,980,560 cost-plus-fixed-fee contract for various support services for the Abrams M1 Tank Family of Vehicles (FoV), M88 Recovery FoVs, Bradley Fighting Vehicles, Assault Breacher Vehicles, and Joint Assault Bridges. Bids were solicited via the internet with one received. Work locations and funding will be determined with each order, with an estimated completion date of March 20, 2029. Army Contracting Command, Detroit Arsenal, Michigan, is the contracting activity (W56HZV-24-D-0010).   

# R&M Consultants Inc., Anchorage, Alaska (W911KB-24-D-0008); Shannon and Wilson Inc., Anchorage, Alaska (W911KB-24-D-0009); and WSP USA Solutions Inc., Washington, D.C. (W911KB-24-D-0010), will compete for each order of the $25,000,000 firm-fixed-price contract for geotechnical design and related services. Bids were solicited via the internet with three received. Work locations and funding will be determined with each order, with an estimated completion date of March 21, 2029. U.S. Army Corps of Engineers, Anchorage, Alaska, is the contracting activity. 

# Foster-Miller Inc., doing business as QinetiQ North America, Waltham, Massachusetts, was awarded a $10,401,796 firm-fixed-price contract for reset, recap, sustainment and maintenance parts, and maintenance services for the Robot Logistics Support Center. Bids were solicited via the internet with one received. Work will be performed in Waltham, Massachusetts, with an estimated completion date of March 21, 2029. Fiscal 2024 other procurement, Army funds were obligated at the time of the award. Army Contracting Command, Detroit Arsenal, Michigan, is the contracting activity (W56HZV-24-D-0021). 

# DMYLES Inc.,* Niagara Falls, New York, was awarded an $8,622,400 firm-fixed-price contract for dredging. Bids were solicited via the internet with four received. Work will be performed in Cleveland, Ohio, with an estimated completion date of Nov. 20, 2024. Fiscal 2024 civil construction funds in the amount of $8,622,400 were obligated at the time of the award. U.S. Army Corps of Engineers, Buffalo, New York, is the contracting activity (W912P4-24-C-0006). 

# Northrop Grumman Systems Corp., Melbourne, Florida, is awarded a $26,219,305 modification (P00031) to a cost-plus-fixed-fee order (N0001921F0889) against a previously issued basic ordering agreement (N0001920G0005). This modification exercises an option to provide sustainment and technical support in support of E-2C/D aircraft common and unique requirements for the governments of France, Japan, Taiwan, and Egypt. Work will be performed in Melbourne, Florida (59.9%); Misawa, Japan (22.6%); Dayton, Ohio (4.4%); St. Augustine, Florida (4.3%); and various locations within the continental U.S. (8.8%), and is expected to be completed in April 2025. Foreign Military Sales customer funds in the amount of $11,500,000 will be obligated at the time of award, none of which will expire at the end of the current fiscal year. Naval Air Systems Command, Patuxent River, Maryland, is the contracting activity.

# CORRECTION: The $55,250,529 time-and-materials contract (W50NH9-24-F-0017) announced on March 20, 2024, for General Dynamics Information Technology Inc., Falls Church, Virginia, to provide sustainment and technical support services for U.S. Army Intelligence and Security Command was actually awarded on March 21, 2024. 
# """

# Where u ask the model what u want it to answer (parse from text)
# Note: works best when we start with "For each ..."
contract_questions = [
    # "For each contract summary, Provide the entire text of the contract.", # context 
    # "For each contract summary, What is the date when the contract was issued?", # date
    "For each contract summary, What is the company name that was awarded the contract?", # company
    "For each contract summary, Where is the company that was awarded the contract located? Identify the City,State.",
    "For each contract summary, How much funding has been awarded in the contract?",
    "For each contract summary, What is the contract awarded for?",
    "For each contract summary, What are the city, state where the contract work will be performed?",
    "For each contract summary, What is the estimated completion date if specified?",
    "For each contract summary, What is the contracting activity group?", 
    "For each contract summary, Where is the contracting activity group located?", 
    "For each contract summary, What is the contracting activity code? The code is typically in parentheses ex: (W56HZV-24-D-0010).", 
    "For each contract summary, Identify the contract type.", 
    "For each contract summary, Determine whether this summary is a modification to a previous contract, assuming False if not specified as a correction.",
    # "For each contract summary, Identify the federal agency responsible for this contract (The same federal agency will be listed above all the contracts it is responsible for)",
]

# And a query intented to prompt a language model to populate the data structure.
def get_query(context: str, questions: List[str]):
    return f"""
            You will be provided a Department of Defense article containing many contract summaries. Please ignore any corrections in the article.
            Answer the questions based only on the following context:
            {context}

            Questions: {' '.join(questions)}
            """

def invoke_query(prompt, model, parser, contract_text):
    chain = prompt | model | parser

    response = chain.invoke({"query": get_query(contract_text, contract_questions)})

    return response


#
# This actually sends the query to the LLM
#
# print(chain.invoke({"query": get_query(contract_text, contract_questions)}))


# ans = "{'contracts': [{'agency': 'Army', 'companies': ['DRS Network & Imaging Systems LLC'], 'awarded': 177980560, 'contract_type': 'cost-plus-fixed-fee'}, {'agency': 'Army', 'companies': ['R&M Consultants Inc.', 'Shannon and Wilson Inc.', 'WSP USA Solutions Inc.'], 'awarded': 25000000, 'contract_type': 'firm-fixed-price'}, {'agency': 'Army', 'companies': ['Foster-Miller Inc.'], 'awarded': 10401796, 'contract_type': 'firm-fixed-price'}, {'agency': 'Army', 'companies': ['DMYLES Inc.'], 'awarded': 8622400, 'contract_type': 'firm-fixed-price'}, {'agency': 'Army', 'companies': ['General Dynamics Information Technology Inc.'], 'awarded': 55250529, 'contract_type': 'time-and-materials'}]}"
# ans = ans.replace('\'', '"')
# print(ans)
# print(json.loads(ans))
batch1 = f"""
BAE Systems Information and Electronic Systems, Fort Wayne, Indiana, was awarded a $459,802,408 order-dependent contract for AN/ARC-231/A Multi-mode Aviation Radio Suite hardware components, repair services and technical/engineering/logistic support. Bids were solicited via the internet with one received. Work locations and funding will be determined with each order, with an estimated completion date of April 9, 2034. Army Contracting Command, Aberdeen Proving Ground, Maryland, is the contracting activity (W56JSR-24-D-0002).
Golden Sands General Contractors Inc., Richmond, Virginia, is being awarded an $11,757,000 firm-fixed-price contract for construction of the Vertical Electro-Magnetic Pulse Simulator (VEMPS) at Patuxent River Naval Air Station.  The work to be performed provides for the construction of a new VEMPS facility which is a small shelter to house the VEMP generator.  Work will be performed in Patuxent River, Maryland, and is expected to be completed by June 2017.  Fiscal 2016 research, development, test and evaluation, (Navy) contract funds in the amount of $11,757,000 are obligated on this award and will not expire at the end of the current fiscal year.  This contract was competitively procured via the Navy Electronic Commerce Online website with two proposals received.  The Naval Facilities Engineering Command, Washington, Washington, District of Columbia, is the contracting activity (N40080-16-C-3015).
General Dynamics NASSCO-Bremerton, Bremerton, Washington, is awarded a $34,305,282 modification to previously awarded contract N00024-14-C-4321 to exercise an option for repair and alteration requirements for USS Carl Vinson (CVN 70) fiscal 2019 dry-docking planned incremental availability (DPIA). The DPIA is the opportunity in the ship’s life cycle to conduct repairs and alterations.  The option will authorize the fourth major availability of the contract, and entails modification and repair of ship equipment, hull and systems. Work will be performed in Bremerton, Washington, and is expected to be completed by July 2020. Fiscal 2019 operations and maintenance (Navy) funding in the amount of $34,305,282 will be obligated at time of award and will expire at the end of the current fiscal year.  Puget Sound Naval Shipyard and Intermediate Maintenance Facility, Bremerton, Washington, is the contracting activity.
Lockheed Martin Rotary and Mission Systems, Moorestown, New Jersey, is being awarded a sole-source, cost-plus-incentive-fee and cost-plus fixed-fee contract.  The total value of this contract is $724,001,438, inclusive of all options.  Under this follow on contract, the contractor will conduct full development and lifecycle engineering for the Aegis Weapon System (AWS) fielding for cruisers, destroyers and Aegis Ashore configurations.  The AWS contract will support the following efforts:  Aegis Baseline (BL) 5.4.1 (Ballistic Missile Defense (BMD) 4.2) development; BL 9 (BMD 5.X) development; Aegis BMD In-Service support; BMD ground and flight test support; modeling and simulation support; Aegis Ashore Missile Defense Test Complex combat system engineering, testing, site support, modernization, technical and logistics support; and Aegis BMD ship installation and planning.  The work will be performed in Moorestown, New Jersey, with an estimated completion date of February 2024.  Fiscal 2020 and fiscal 2021 research, development, test, and evaluation; and fiscal 2021 procurement defense wide, and operations and maintenance funds in the amount of $45,036,867, will be obligated at the time of award.  The Missile Defense Agency, Dahlgren, Virginia, is the contracting activity (HQ0851-21-C-0002).
SupplyCore Inc.,* Rockford, Illinois, has been awarded a maximum $15,000,000 firm-fixed-price, indefinite-delivery/indefinite-quantity, prime-vendor bridge contract for maintenance, repair, and operations for the North central region.  This contract was a sole-source acquisition. Location of performance is Illinois with a Feb. 27, 2015, performance completion date.  Using military services are Army, Navy, Air Force, Marine Corps, and federal civilian agencies.  Type of appropriation is fiscal 2015 defense working capital funds.  The contracting activity is the Defense Logistics Agency Troop Support, Philadelphia, Pennsylvania (SPE8E3-15-D-0004).
Lockheed Martin Corp., Grand Prairie, Texas, was awarded a $6,068,344,959 firm-fixed-price contract for incidental services, hardware, facilities, equipment and all technical, planning, management, manufacturing and testing efforts to produce Phased Array Tracking Radar to Intercept on Target Advanced Capability-3 missiles, missile segment enhancement configuration and associated ground support equipment and spares.  Bids were solicited via the internet with one received.  Work will be performed in Huntsville, Alabama; Camden, Arkansas; Ocala, Florida; Chelmsford, Massachusetts; Grand Prairie and Lufkin, Texas; and Archbald, Pennsylvania, with an estimated completion date of June 30, 2027.  Fiscal 2020 missile procurement (Army) funds in the amount of $6,068,344,959 were obligated at the time of the award.  U.S. Army Contracting Command, Redstone Arsenal, Alabama, is the contracting activity (W31P4Q-20-C-0023).
BAE Systems Norfolk Ship Repair Inc., Norfolk, Virginia, is being awarded a $55,766,162 modification to a previously awarded contract (N00024-11-C-4407) for USS Wasp (LHD-1) fiscal 2017 planned maintenance availability. A planned maintenance availability includes the planning and execution of depot-level maintenance, alterations, and modifications that will update and improve the ship's military and technical capabilities. Work will be performed in Norfolk, Virginia, and is expected to be completed by May 2017. Fiscal 2017 operations and maintenance (Navy); and other procurement (Navy) funding in the amount of $55,766,162 will be obligated at time of award and $55,285,426 will expire at the end of the current fiscal year. The Mid-Atlantic Regional Maintenance Center, Norfolk, Virginia, is the administrative contracting activity.
Dawson Enterprises LLC, Honolulu, Hawaii, has been awarded a $21,357,584 firm-fixed-price contract for construction of modular buildings. Contractor will provide all site preparation and construction of modular buildings. Work will be performed at Eglin Air Force Base, Florida, and is expected to be complete by Aug. 31, 2017. This award is the result of a sole-source acquisition. Fiscal 2016 and 2017research, development, test, and evaluation funds in the amount of $12,700,000 are being obligated at the time of award. Air Force Test Center, Eglin Air Force Base, Florida, is the contracting activity (FA2823-17-C-4010).
General Dynamics Land Systems, Sterling Heights, Michigan, has been awarded a $59,223,559 firm-fixed-price contract for new improved fire control electronics units (IFCEU); repaired and upgraded IFCEUs; and repaired and upgraded improved commanders display unit to support the M1-A2 System Enhanced Package Version 2 Field Modification program. One bid was solicited with one bid received. Work locations and funding will be determined with each order, with an estimated completion date of Sept. 28, 2022. U.S. Army Contracting Command, Warren, Michigan, is the contracting activity (W56HZV-17-D-0098).
Raytheon Missiles & Defense, Tucson, Arizona, is awarded a $78,665,000 firm-fixed-price modification to previously awarded contract N0002421C5408 to exercise options for additional fiscal 2022 guided missile assemblies in support of the fiscal 2021-2023 Evolved Seasparrow Missile (ESSM) Block 2 full rate production requirements. Work will be performed in Tucson, Arizona (46%); Edinburgh, Australia (8%); San Jose, California (7%); Raufoss, Norway (7%); Mississauga, Canada (6%); Ottobrunn, Germany (4%); Cambridge, Canada (3%); Nashua, New Hampshire (3%); Hengelo Ov, Netherlands (2%); Koropi Attica, Greece (2%); Torrance, California (2%); Canton, New York (2%); Ankara, Turkey (1%); Grenaa, Denmark (1%); Westlake Village, California (1%); and various other locations each less than 1% (5%), and is expected to be completed by March 2025. Fiscal 2022 weapons procurement (Navy) in the amount of $78,665,000 will be obligated at time of award and will not expire at the end of the current fiscal year. The Naval Sea Systems Command, Washington, D.C., is the contracting activity.
Capco Inc., Grand Junction, Colorado, is being awarded a $39,899,997 five-year, indefinite-delivery/indefinite-quantity contract for the manufacture of the WA83, CCU-136A/A impulse cartridge; and/or WB24, CCU-145A impulse cartridge; and/or production lot testing used for ejection devices from aircrafts. Work will be performed in Grand Junction, Colorado, and the ordering period is expected to be completed by March 2023. This effort combines purchases with fiscal 2018 ammunition procurement (Air Force; 86.56 percent); United Kingdom (2.95 percent); Korea (2.68 percent); Netherlands (2.03 percent); Austria (1.93 percent); fiscal 2018 aircraft procurement (Air Force; 1.23 percent); Australia (1.17 percent); Japan (0.99 percent); Israel (0.43 percent); and Brazil (0.03 percent), under the Foreign Military Sales program. Funds in the amount of $2,102,238 will be obligated at the time of award and funds will not expire at the end of the current fiscal year. This contract was competitively procured with the solicitation posted to the Federal Business Opportunities websiteas a 100 percent small business set-aside requirement, with one offer received. Naval Supply Systems Command Weapon Systems Support, Mechanicsburg, Pennsylvania, is the contracting activity (N00104-18-D-NF01).
Physical Optics Corp.,* Torrance, California, is awarded an $8,631,282 firm-fixed-price indefinite-delivery/indefinite-quantity contract.  This contract provides for the design, test, production and delivery of up to 503 C-Band radar tracking transponders in support of the Aerial Targets program.  Work will be performed in Torrance, California, and is expected to be completed in October 2024.  No funds will be obligated at the time of award.  Funds will be obligated on individual orders as they are issued.  This contract was competitively procured as a small business set-aside via an electronic request for proposal; three offers were received.  The Naval Air Warfare Systems Command, Patuxent River, Maryland, is the contracting activity (N00019-20-D-0005)."""

batch2 = f"""
Tetra Tech Inc., Norfolk, Virginia, is awarded a $90,000,000 cost-plus-award-fee modification to previously-awarded, indefinite-delivery/indefinite-quantity contract N62470-16-D-9008 to increase the maximum dollar value and extend the period of performance for comprehensive long-term environmental architect-engineering services on Navy and Marine Corps installations at sites in the Naval Facilities Engineering Systems Command Atlantic area of responsibility. This modification increases the total cumulative value of the contract to $368,000,000. Work will be performed in Maryland (13%), Pennsylvania (13%), Florida (11%), Rhode Island (8%), Washington (8%), California (7%), Massachusetts (6%), Texas (6%), Mississippi (5%), New York (4%), Maine (3%), Arizona (2%), Connecticut (2%), Indiana (2%), Louisiana (2%), New Jersey (2%), South Carolina (2%), Georgia (1%), Illinois (1%), North Carolina (1%), and Nevada (1%), and is expected to be completed by April 2022. No funds will be obligated at time of award. Funds will be obligated on individual task orders as they are issued. Task orders will be primarily funded by environmental restoration (Navy) funds. The Naval Facilities Engineering Systems Command Atlantic, Norfolk, Virginia, is the contracting activity.
Rockwell Collins Inc., Cedar Rapids, Iowa, was awarded a cost-plus-fixed-fee and firm-fixed-price, indefinite-delivery requirements contract of $21,121,700. The award will provide support that will include obsolescence, engineering reach back, repairs, buys, software and firmware updates and future electromagnetic compatibility testing. Work will be performed at the contractor’s facility in Cedar Rapids, Iowa, and is estimated to be completed by April 8, 2029. This award is the result of a sole-source acquisition and is being funded with U.S. Special Operations Command procurement funds. This is a terms and conditions basic contract with no funding obligated at time of award. Funding will be obligated with individual delivery and task orders. The contracting activities are the Air Force Life Cycle Management Center (AFLCMC)/WIUKA and AFLCMC/WIUKB, Robins Air Force Base, Warner Robins, Georgia (FA8509-24-D-0001). 
McMurdo Group, Lanham, Maryland, was awarded a $33,986,800 indefinite-delivery/indefinite-quantity contract for The Personnel Recovery Support System Personnel Recovery Device. Five bids were solicited with five bids received. Work locations and funding will be determined with each order, with an estimated completion date of March 6, 2022. U.S. Army Contracting Command, Aberdeen Proving Ground, Maryland, is the contracting activity (W91CRB-18-D-0004)."
Northrop Grumman Aerospace Systems, Redondo Beach, California, is being awarded $21,527,216 for cost-plus fixed fee contract modification P00023 under a previously awarded contract (N00014-16-C-1009) for the Solid State High Power Laser Weapon System Demonstrator program.With award of this modification, the total cumulative value of this contract is $144,994,264.Work will be performed in Redondo Beach, California, and is expected to be completed Aug. 31, 2019.Fiscal 2017 research, development, test and evaluation (Navy) funds in the amount of $14,926,303 will be obligated at the time of award.No funds will expire at the end of the current fiscal year.The base contract was competitively procured under Office of Naval Research broad agency announcement 15-0005, with six proposals received in response to the solicitation.The Office of Naval Research, Arlington, Virginia, is the contracting activity.
Insitu Inc., Bingen, Washington, is awarded a $160,317,104 firm-fixed-price, indefinite-delivery/indefinite-quantity contract. This contract provides training, test and engineering, development of engineering change proposals, operations support, organizational level maintenance, field service representatives, land and ship surveys, hardware site activations, hardware installs, repairs, and development of noncommercial software and data in support of RQ-21A Blackjack and ScanEagle unmanned aircraft platforms. Work will be performed in Bingen, Washington (88%); and various locations outside the continental U.S. (12%), and is expected to be completed in June 2026. No funds will be obligated at the time of award; funds will be obligated on individual orders as they are issued. The contract was not competitively procured pursuant to 10 U.S. Code 2304(c)(1). The Naval Air System Command, Patuxent River, Maryland, is the contracting activity (N0001922D0038). 
Tecan US Inc., Morrisville, North Carolina, has been awarded a $32,862,500 firm-fixed-price contract for robotic pipette tips.  The scope of this contract effort includes the expansion of the U.S. domestic production capacity for robotic pipette tips by standing up infrastructure and increasing production capacity with Tecan US Inc.  The COVID-19 pandemic has created a requirement for additional near term diagnostic testing capability which significantly exceeds manufacturing capacity of sample collection and processing consumables.  This project will create Tecan’s capacity to produce up to 40 million pipette tips per month domestically.  Work will be completed in Morrisville, North Carolina, and is expected to be completed November 2022.  This award is the result of a Commercial Solutions Opening (CSO) request issued by the Joint Rapid Acquisition Cell (JRAC) and is a full and open competition.  The solicitation was published by Department of Health and Human Services and JRAC in the CSO in August 2020.  Fiscal other procurement funds are being used on this contract.  The Air Force Life Cycle Management Center, Hanscom Air Force Base, Massachusetts, is the contracting activity (FA8730-20-S-0003).
DRS Advanced ISR LLC, Beavercreek, Ohio, was awarded a $15,730,000 firm-fixed-price contract for the sustainment to include engineering change proposals for obsolescence, procurement of spares, retrofit kits, test program kits, test program sets, and other engineering logistics services for the AN/URC-145A(V) Joint Tactical Terminal-Integrated Broadcast Service. One bid was solicited and one bid received. Work will be performed in Beavercreek, Ohio, with an estimated completion date of June 30, 2022. Fiscal 2017 other procurement (Army) will be determined with each order. U.S. Army Contracting Command, Aberdeen Proving Ground, Maryland, is the contracting activity (W56KGY-17-D-0017).
Pratt & Whitney Military Engines, East Hartford, Connecticut, has been awarded a maximum $15,000,000 time and materials contract for program and engineering labor hours for warming up TF-33 cold start parts. This was a sole-source acquisition using justification 10 U.S. Code 2304 (c)(1), as stated in Federal Acquisition Regulation 6.302-1. This is a one-year contract with no option periods. Location of performance is Connecticut, with a Feb. 10, 2023, performance completion date. Using military service is Air Force. Type of appropriation is fiscal 2022 through 2023 defense working capital funds and appropriated funds. The contracting activity is the Defense Logistics Agency Aviation, Richmond, Virginia (SPE4A2-22-D-0004). 
Northrop Grumman Systems Corp., Melbourne, Florida, is awarded a $12,970,550 modification (P00005) to a cost-plus-fixed-fee order (N0001920F5008) against a previously issued basic ordering agreement (N0001920G0005). This modification exercises an option to provide continued support for integrated test team operations in executing advanced development experimentation flights and development testing in support of future delta system software builds for the Navy E-2D Advanced Hawkeye aircraft.  Work will be performed in Patuxent River, Maryland, and is expected to be completed in July 2022.  Fiscal 2021 research, development, test and evaluation (Navy) funds in the amount of $1,632,077 will be obligated at time of award, none of which will expire at the end of the current fiscal year. The Naval Air Systems Command, Patuxent River, Maryland, is the contracting activity.
MW Builders Inc., Pflugerville, Texas, was awarded a $36,514,000 firm-fixed-price contract to design and construct a new unaccompanied enlisted personnel housing facility. Bids were solicited via the internet with four received. Work will be performed in Fort Hood, Texas, with an estimated completion date of July 3, 2023. Fiscal 2020 military construction, Army funds in the amount of $36,514,000 were obligated at the time of the award. U.S. Army Corps of Engineers, Fort Worth, Texas, is the contracting activity (W9126G-21-C-0014). 
Communication & Power Industries (Econco division), Woodland, California, is awarded $28,152,432 for a firm-fixed-price requirements contract for the repair of single switch tubes and double duty switch tubes that are components of the AN/SPY radar systems in support of the Aegis Combat System. This is a five-year contract with no options. All work will be performed in Woodland, California, and the ordering period is expected to be completed by September 2028. Working capital funds (Navy) will be obligated as individual task orders are issued, and funds will not expire at the end of the current fiscal year. One company was solicited for this sole-source requirement pursuant to the authority set forth in 10 U.S. Code 3204 (a)(1), with one offer received. Naval Supply Systems Command Weapon Systems Support, Mechanicsburg, Pennsylvania, is the contracting activity (N00104-23-D-SX02).
Baron Communications,* Newport News, Virginia, is awarded a $10,494,756 firm-fixed-price, indefinite-delivery/indefinite-quantity contract for electrical maintenance and repair services. This contract provides for facility investment services for electrical maintenance and repair services. Work will be performed at Naval Station Norfolk, Virginia (73%); Norfolk Naval Shipyard, Virginia (22%); Naval Weapon Station Yorktown, Virginia (3%); Naval Air Station Oceana, Virginia (1%); Joint Expeditionary Base Little Creek-Fort Story, Virginia (1%); and other Hampton Roads, Virginia, locations and is expected to be completed by September 2024. Fiscal 2023 operation and maintenance (Navy) funds in the amount of $97,479 will be obligated via recurring work task order issued at time of award and will expire at the end of the current fiscal year. This contract was competitively procured via the sam.gov website, with two offers received. Naval Facilities Engineering Systems Command, Mid-Atlantic, Norfolk, Virginia, is the contracting activity (N4008523D2502).
"""

batch3 = f"""
Orbital Research Inc., Cleveland, Ohio, was awarded an $8,257,426 firm-fixed-price contract for 1,700 drop-glide munitions, and 24 unmanned aerial systems and weapon release systems. Bids was solicited via the internet with one received. Work will be performed in Benning, Georgia; Picatinny, New Jersey; and Twenty-Nine Palms, California, with an estimated completion date of Sept. 22, 2023. Fiscal 2022 procurement, Defense-Wide funds in the amount of $1,535,698 were obligated at the time of the award. U.S. Army Contracting Command, Detroit Arsenal, Michigan, is the contracting activity (W56HZV-22-C-0073).
Oregon Department of Fish and Wildlife, Salem, Oregon, was awarded a $7,887,876 modification (P00004) to contract W9127N-20-C-0028 for electric power support. Work will be performed in Trail, Oregon, with an estimated completion date of Aug. 31, 2023. Fiscal 2022 other procurement, Army funds in the amount of $7,887,876 were obligated at the time of the award. U.S. Army Corps of Engineers, Portland, Oregon, is the contracting activity.
PC Mechanical Inc., Santa Maria, California, is awarded a $62,000,000 indefinite-delivery/indefinite-quantity contract for equipment support services (ESS) supporting the civil engineering support equipment (CESE) at Naval Base Ventura County, Naval Base San Diego, and Naval Construction Battalion Center. Work will be performed in Santa Maria, California (75%); and Gulfport, Mississippi (25%). No task orders are being issued at this time. The term of the contract is not to exceed 60 months with a six-month option. Expected completion date of February 2027. The work to be performed is for ESS on CESE assets in contiguous U.S. locations. The contractor shall provide all labor, training, management, for the inspections, preventative maintenance, refurbishment, repairs, overhauls, upgrades, modernization, modifications, and logistics management information services provided to support of naval expeditionary equipment assets. Fiscal 2021 operation and maintenance (Navy) contract funds in the amount of $10,000 will be obligated after award and will expire at the end of the current fiscal year. Future task orders will be primarily funded by operations and maintenance (Navy). This contract was competitively procured via the system for Award Management Contract Opportunities website with one proposal received. The Naval Facilities Engineering Systems and Expeditionary Warfare Center, Port Hueneme, California, is the contracting activity (N39430-21-D-2207).
B. L. Harbert International, Birmingham, Alabama, is awarded a $32,873,962 firm-fixed-price task order (N6945021F0566) under a multiple award construction contract for hangar renovations and repairs at Naval Air Station Corpus Christi, Texas. The task order also contains one unexercised option, which if exercised would increase the cumulative task order value to $33,696,344. Work will be performed in Corpus Christi, Texas, and is expected to be completed by November 2023.  The work to be performed provides for the repair, and renovation of Corpus Christi Army Depot Hangar 47.  Work includes miscellaneous site work, structural stabilization, removal and replacement of the exterior envelope, renovation of the hangar bay and the office lean-to wings, the provision of two elevators, removal and replacement of building systems such as heating, ventilation, and air conditioning, power and lighting and telecommunication systems.  The option, if exercised, provides for work on exterior trench drains, piping and the retention area. Fiscal 2021 operation and maintenance (Army) funds in the amount of $32,873,962 are obligated on this award and will expire at the end of current fiscal year. Three proposals were received for this task order.  The Naval Facilities Engineering Systems Command, Southeast, Jacksonville, Florida, is the contracting activity (N69450-19-D-0908).
Stratascor LLC, Virginia Beach, Virginia, is awarded a $210,000,000 indefinite-delivery/indefinite-quantity, fixed-price contract for command, control, communications, and computer system afloat operations and sustainment support for capabilities aboard the Military Sealift Command (MSC) fleet of ships, and the MSC network operations centers. This contract includes a five-year ordering period. Work will be performed in Norfolk, Virginia, and is scheduled to commence Jan. 1, 2018, and is expected to be completed Dec. 31, 2023.  Navy working capital funds and U.S. Transportation Command working capital funds in the amount of $500,000 will be obligated at the time of award.  Funds will not expire at the end of the current fiscal year.  This contract was competitively procured, with proposals solicited via the Federal Business Opportunities website, with five offers received.  The Navy’s Military Sealift Command, Norfolk, Virginia, is the contracting activity (N3220519D1000).
Offshore Service Vessels LLC, Cut Off, Louisiana, is awarded a $10,493,750 firm-fixed-price contract with reimbursable elements for the West Coast Naval Special Warfare submarine support vessel MV Alyssa Chouest. This vessel will be utilized to launch and recover submersibles, divers and small craft. This contract includes a 12-month base period, three 12-month option periods, and one 11-month option period.  If all options are exercised this would bring the cumulative value of the contract to $54,238,356.  Work will be performed in Pearl Harbor, Hawaii, and at sea, and is expected to be completed July 9, 2020. If all options are exercised, work will continue through June 8, 2024.  Fiscal 2019 Navy working capital funds in the amount of $2,415,000 will be obligated at the time of award, and will expire at the end of the current fiscal year.  This contract was competitively procured with 50 plus proposals solicited via the Federal Business Opportunities website, with six offers received. The Navy’s Military Sealift Command Norfolk, Virginia, is the contracting activity (N3220519C3518).
The Boeing Co., St. Louis, Missouri, is awarded a $10,802,192 modification (P00012) to a cost-plus-fixed-fee order (N0001917F0005) against a previously issued basic ordering agreement (N0001916G0001). This modification exercises options to procure 359 Primary Bleed Air Pressure Regulator (PBAR) valves in support of the Environmental Control System PBAR and Shut Off Valve Improvement modifications to the F/A-18 E/F and EA-18G aircraft. Work will be performed in Windsor, Connecticut (80%); El Segundo, California (12%); and St. Louis, Missouri (8%), and is expected to be completed in June 2024. Fiscal 2022 aircraft procurement (Navy) funds in the amount of $10,802,192 will be obligated at time of award, none of which will expire at the end of the current fiscal year. The Naval Air Systems Command, Patuxent River, Maryland, is the contracting activity.
Raytheon Integrated Defense Systems, Portsmouth, Rhode Island, is awarded an $8,230,603 cost-plus-fixed-fee modification to previously awarded contract N00024-16-C-5418 to exercise options for NATO Sea Sparrow missile system design agent engineering and technical support services. Work will be performed in Portsmouth, Rhode Island (94%); Marlborough, Massachusetts (3%); and San Diego, California (3%), and is expected to be completed by November 2020. Fiscal 2018 other procurement (Navy); fiscal 2019 research, development, test and evaluation (Navy); non-expiring other funds; and Foreign Military Sales funding in the amount of $4,251,731 will be obligated at time of award, and $2,162,681 will expire at the end of the current fiscal year. The Naval Sea Systems Command, Washington, District of Columbia, is the contracting activity.
ENGlobal Government Services Inc., Tulsa, Oklahoma, has been awarded a maximum $11,552,569 cost-plus-fixed-fee, bridge contract for automated fuel handling maintenance. This was a sole-source acquisition using justification 10 U.S .Code 2304 (c)(1), as stated in Federal Acquisition Regulation 6.302-1. This is a 15-month base contract with one three-month option period. Locations of performance are Virginia, Georgia, Hawaii, California, Washington, Florida, North Carolina, South Carolina, Oklahoma, Spain, Greenland and Japan, with a May 12, 2021, performance completion date. Using military services are Army, Navy, Air Force, Marine Corps, National Guard and Coast Guard. Type of appropriation is fiscal 2020 through 2021 defense working capital funds. The contracting activity is the Defense Logistics Agency Contracting Services Office, Columbus, Ohio (SP4702-20-C-0002).
Lockheed Martin Corp., Lockheed Martin Aeronautics Co., Fort Worth, Texas, is being awarded a $257,780,849 firm-fixed-price modification to the previously awarded low-rate initial production lot 10 F-35 Lightning II advance acquisition contract (N00019-15-C-0003).  This modification provides the procurement of 129 alternate mission equipment for the Air Force (54); Navy and Marine Corps (11); foreign military sales (FMS); and international partners (39); 468 pilot flight equipment for the Air Force (203); Navy and Marine Corps (131); and FMS and international partners (134); and 94 red gear for the Air Force (44); Navy and Marine Corps (11); FMS; and international partners (39), to support the F-35 Joint Strike Fighter production.  Work will be performed in Inglewood, California (60 percent); White Plains, New York (25 percent); St. Petersburg, Florida (5 percent); Orlando, Florida (5 percent); and Fort Worth, Texas (5 percent), and is expected to be completed in June 2020.  Fiscal 2016 aircraft procurement (Air Force, Navy, Marine Corps); international partner; and FMS funds in the amount of $257,780,849 are being obligated at time of award, none of which will expire at the end of the current fiscal year.  This order combines purchases for the Air Force ($122,909,691; 47.7 percent); Marine Corps ($40,406,910; 15.6 percent); Navy ($10,285,742; 4.0 percent); international partners ($60,260,604; 23.4 percent); and FMS customers ($23,917,602; 9.3 percent) under the Foreign Military Sales program.  The Naval Air Systems Command, Patuxent River, Maryland is the contracting activity.
Fluor Federal Solutions LLC, Greenville, South Carolina, is being awarded a $48,097,133 modification under a previously awarded indefinite-delivery/indefinite-quantity contract (N69450-12-D-7582) to exercise option three for base operations support services at various installations in the Naval Facilities Engineering Command Southeast area of responsibility.  The work to be performed provides for regional base operating support services including, but not limited to, the following functions: port operations, facilities support services, facility investment, base support vehicles and equipment, and environmental.  After award of this option, the total cumulative contract value will be $275,552,389.  Work will be performed in Jacksonville, Florida, and is expected to be completed June 2018.  No funds will be obligated at time of award.  Fiscal 2017 operations and maintenance (Navy and Marine Corps); 2017 Navy working capital funds; 2017 defense health program; and 2017 family housing operations and maintenance (Navy) contract funds in the amount of $38,952,862 for recurring work will be obligated on individual task orders issued during the option period.  The Naval Facilities Engineering Command, Southeast, Jacksonville, Florida, is the contracting activity.
"""

model_batch = f"""
Beechcraft Defense Co., Wichita, Kansas, has been awarded a $60,523,373 firm-fixed-price, cost-plus-fixed-fee contract for Joint Primary Aircraft Training System (T-6) program management and sustainment engineering. Contractor will provide program management, engineering services, sustaining engineering, field service representatives, deficiency reporting and maintenance requests for support. It also includes diminishing manufacturing sources and material sources, technical manual updates, configuration and data management, and aircraft, engine, and mechanical structural integrity efforts. Work will be performed at Wichita, Kansas, and is expected to be complete by April 30, 2021. This award is the result of a sole-source acquisition. Fiscal 2017 operations and maintenance funds in the amount of $9,232,172 are being obligated at the time of award. Air Force Life Cycle Management Center, Wright-Patterson Air Force Base, Ohio, is the contracting activity (FA8617-17-C-6211).
Huntington Ingalls Inc., Ingalls Shipbuilding Division, Pascagoula, Mississippi, is being awarded a $7,016,664 cost-plus-fixed fee contract for post-delivery planning yard services in support of the LHA-7 amphibious assault ship.  The services include post-delivery planning, material procurement and support services for industrial post-delivery availability, post-delivery availability, fitting-put availability, post shakedown availability and emergent work.  The contract includes options which, if exercised, would bring the cumulative value of this contract to $90,000,000. Fiscal 2012 shipbuilding and conversion (Navy) funding in the amount of $7,016,664 will be obligated at time of award and will not expire at the end of the fiscal year.  Work will be performed in Pascagoula, Mississippi, and is expected to be completed by August 2020.  This contract was not competitively procured per Federal Acquisition Regulation 6.302-1 - only one responsible source and no other supplies or services will satisfy agency requirements. The Naval Sea Systems Command, Washington, District of Columbia, is the contracting activity (N00024-17-C-2473).=
Pond Constructors, Norcross, Georgia, was awarded a $9,634,613 modification (0014) to contract W912DY-13-G-0004 for recurring maintenance and minor repair for Defense Logistics Agency capitalized equipment and appurtenances. Work will be performed in Honolulu, Hawaii; Japan; and British Indian Ocean Territory, with an estimated completion date of April 13, 2022. Fiscal 2017 other funds in the amount of $9,634,613 were obligated at the time of the award. U.S. Army Corps of Engineers, Huntsville, Alabama, is the contracting activity.
The Boeing Co., Huntington Beach, California, has been awarded a $7,576,425 cost-plus-fixed-fee contract modification (P00003) for a within-scope change to a previously awarded contract (HR0011-16-C-0114) to provide continued support for a research project under the Hydra Phase 2 program. Fiscal 2017 research and development funds in the amount of $645,510 are being obligated at the time of award. Work will be performed in Huntington Beach, California (65 percent); Santa Fe Springs, California (7 percent); Anaheim, California (5 percent); Attleboro, Massachusetts (5 percent); Long Beach, California (5 percent); Placentia, California (2 percent); Huntsville, Alabama (1 percent); and Garden Grove, California (1 percent). Additionally, nine percent of the effort will be performed at multiple locations (each location under 1 percent of the effort). The contract has an estimated completion date of January 2019. The Defense Advanced Research Projects Agency, Arlington, Virginia, is the contracting activity.
URS Federal Services Inc., Germantown, Maryland, has been awarded a maximum $74,999,999 hybrid fixed-price incentive firm target, cost reimbursement no fee, cost-plus-fixed-fee, firm-fixed-price contract for warehousing and distribution support services. This is a five-year contract with no option periods. This was a competitive contract with three responses received. Locations of performance are Maryland and Utah, with an April 30, 2022, performance completion date. Using customer is Defense Logistics Agency. Type of appropriation is fiscal 2017 through 2022 defense working capital funds. The contracting activity is the Defense Logistics Agency Distribution, New Cumberland, Pennsylvania (SP3300-17-D-5001).
VIASAT Inc., Carlsbad, California, was awarded a non-competitive, firm-fixed-price contract for the production of ground transceivers for the Blue Force Tracker 2 program.  The total value of this action (including options) is $13,680,000 funded by fiscal 2017 procurement funds.  Performance will be at the contractor’s facility until the transceivers are delivered to the government.  This is a sole-source contract.  Deliveries will take place from September 2017 through April 2018.  The Defense Information Technology Contracting Organization, Scott Air Force Base, Illinois, is the contracting activity (HC1028-17-C-0010).  
Leidos Inc., Reston, Virginia, has been awarded a $8,062,880 cost-plus-fixed-fee contract to investigate, develop and ultimately transition nonlinear transmission line (NLTL) or other solid-state-based high-power electromagnetics weapon concepts. The work includes developing devices, including suitable user interfaces, embedded controls and diagnostics using an NLTL or alternative solid-state high-power microwave source. Work will be performed at Kirtland Air Force Base, New Mexico, and is expected to be complete by Dec. 2026. This award is the result of a competitive acquisition with four offers were received. Fiscal 2022 and 2023 research, development, test and evaluation funds in the amount of $1,565,752 will be obligated at the time of award. Air Force Research Laboratory, Kirtland AFB, New Mexico, is the contracting activity (FA9451-23-C-A003).
Lockheed Martin Aeronautics Co., Fort Worth, Texas, is awarded a $24,432,476 cost-plus-fixed-fee modification (P00003) to a previously awarded indefinite delivery/indefinite quantity contract (N0001922D0024). This modification adds scope for maintenance and support of F-35 chase aircraft necessary to support F-35 aircraft acceptance and delivery, including all pre and post-flight activities, the removal and replacement of failed components, and return the aircraft to a clean and compliant condition suitable for first-time delivery of F-35 Air Force, Navy and Marine Corps, non-U.S. Department of Defense participants, and Foreign Military Sales customer's operational aircraft. Work will be performed in Fort Worth, Texas, and is expected to be completed in December 2023. No funds are being obligated at time of award; funds will be obligated on individual orders as they are issued. The Naval Air Systems Command, Patuxent River, Maryland, is the contracting activity.
Outdoor Venture Corp.,** Stearns, Kentucky, has been awarded a maximum $76,701,761 firm-fixed-price, indefinite-delivery/indefinite-quantity contract for military standard tents and components. This was a competitive acquisition with two responses received. This contract includes two one-year tiers. The performance completion date is Aug. 31, 2025. Using military services are Army, Navy, Air Force and Marine Corps. Type of appropriation is fiscal 2023 through 2025 defense working capital funds. The contracting activity is the Defense Logistics Agency Troop Support, Philadelphia, Pennsylvania (SPE1C1-23-D-0002). 
Pfizer Inc., New York, New York, was awarded a $1,959,999,848 modification (P00005) to contract W58P05-22-C-0001 for the oral therapeutic Paxlovid. Work will be performed in New York, New York, with an estimated completion date of Dec. 31, 2028. Fiscal 2021 Coronavirus Preparedness Response and Relief Supplemental Appropriations Act funds in the amount of $1,959,999,848 were obligated at the time of the award. U.S. Army Contracting Command, New Jersey, is the contracting activity.
USA Environmental Inc.,* Oldsmar, Florida (N62473-23-D-2211); Engineering/Remediation Resources Group Inc.,* Martinez, California (N62473-23-D-2212); EA-Relyant JV,* Hunt Valley, Maryland (N62473-23-D-2213); HL/VRH Federal Services LLC,* Maxton, North Carolina (N62473-23-D-2214); PIKA-Insight JV LLC,* Stafford, Texas (N62473-23-D-2215); and Bering Sea Eccotech LLC,* Anchorage, Alaska (N62473-23-D-2216), are awarded a combined maximum value $95,000,000 firm-fixed price, indefinite-delivery/indefinite-quantity, multiple-award contract for range sustainment and remediation services for Naval Facilities Engineering Systems Command (NAVFAC) Southwest. Work will performed primarily within the NAVFAC Southwest area of responsibility including California (93%); Arizona (6%); and various locations within the U.S. (less than 1%). Each awardee will be awarded $5,000 to satisfy the minimum guarantee. Fiscal 2023 operation and maintenance (Navy) funds in the amount of $30,000 will be obligated at time of award and will expire at the end of the current fiscal year. This contract was competitively procured via the System for Award Management website, with seven offers received. The Naval Facilities Engineering Systems Command Southwest, San Diego, California, is the contracting activity.
USA Environmental Inc.,* Oldsmar, Florida, is awarded a maximum-value $95,000,000 cost-plus-award-fee, indefinite-delivery/indefinite-quantity contract for munitions response services for projects at various locations within the Naval Facilities Engineering Systems Command (NAVFAC) Atlantic area of responsibility and potentially at other sites worldwide. Work will be performed primarily in Vieques, Puerto Rico (70%); Hawaii (20%); Washington (5%); North Carolina (2%); Virginia (2%); and Florida (1%), and is expected to be completed by December 2027. Fiscal 2023 environmental restoration (Navy) funds in the amount of $10,000 will be obligated at time of award in order to satisfy the minimum guarantee and will not expire at the end of the current fiscal year. This contract was competitively procured via the System for Award Management contract opportunities website, with two offers received. The Naval Facilities Engineering Systems Command Atlantic, Norfolk, Virginia, is the contracting activity (N62470-23-D-0002).
Alliant Techsystems Operations LLC, doing business as ATK Tactical Propulsion and Control, Rocket Center, West Virginia, has been awarded an estimated $67,000,000 indefinite-delivery/indefinite-quantity contract for production of SR-116 rocket motors for the AIM-9P rocket. Work will be performed at Rocket Center, West Virginia, and is expected to be complete by Feb. 27, 2022. This contract is 100 percent foreign military sales, with foreign country military funds in the amount of $8,355,047 being obligated at time of award for the first delivery order to Bahrain, Taiwan and Egypt. The Robins Air Logistics Center, Robins Air Force Base, Georgia, is the contracting activity (FA8520-17-D-0002).
Defense Acquisition Support Services LLC,* Long Branch, New Jersey, was awarded a $15,282,334 cost-plus-fixed-fee contract for support services to U.S. Army Communications and Electronics Command. Bids were solicited via the Internet with two received. Work will be performed in Aberdeen, Maryland, with an estimated completion date of Sept. 1, 2020. Fiscal 2017 other; and operations and maintenance (Army) funds in the collective amount of $1,700,000 were obligated at the time of the award. U.S. Army Contracting Command, Aberdeen, Maryland, is the contracting activity (W56KGY-17-C-0007).
Hitachi Aloka Medical America Inc., Wallingford, Connecticut, has been awarded a maximum $162,760,750 firm-fixed-price, indefinite-delivery/indefinite-quantity contract for radiology systems, accessories and training. This is a five-year base contract with one five-year option period. This was a competitive acquisition with 27 responses received. Location of performance is Connecticut, with a Feb. 28, 2022, performance completion date. Using customers are Air Force, Army, Navy, Marine Corps and federal civilian agencies. Type of appropriation is fiscal 2017 through 2022 defense working capital funds. The contracting activity is the Defense Logistics Agency Troop Support, Philadelphia, Pennsylvania (SPE2D1-17-D-0024).
L-3 Communications Vertex Aerospace, Madison, Mississippi, is being awarded $15,049,163 for firm-fixed-price modification P00063 to a previously awarded indefinite-delivery requirements contract (N00019-11-D-0010) for aircraft maintenance and logistical life cycle support for the C-12 utility lift aircraft.  Work will be performed in Corpus Christi, Texas (42 percent); Patuxent River, Maryland (6 percent); Guantanamo Bay, Cuba (6 percent); Bahrain (6 percent); Atsugi, Japan (6 percent); Beaufort, South Carolina (4 percent); San Angelo, Texas (4 percent);  Yuma, Arizona (4 percent); New Orleans, Louisiana (4 percent); Iwakuni, Japan (4 percent); New River, North Carolina (3 percent); Kadena, Japan (3 percent); Manassas, Virginia (2 percent); Miramar, California (2 percent); Futenma, Japan (2 percent); and Misawa, Japan (2 percent), and is expected to be completed in June 2017.  Funds will not be obligated at time of award; funds will be obligated on individual delivery orders as they are issued.  The Naval Air Systems Command, Patuxent River, Maryland, is the contracting activity.  
"""

if __name__ == "__main__":
    model = ChatOpenAI(model="gpt-3.5-turbo", api_key=os.environ.get("OPENAI_KEY"), temperature=0)
    # Set up a parser + inject instructions into the prompt template.
    parser = JsonOutputParser(pydantic_object=Article)

    prompt = PromptTemplate(
        template="Answer the user query based only on the provided contract summary.\n{format_instructions}\n{query}\n",
        input_variables=["context", "query"],
        partial_variables={"format_instructions": parser.get_format_instructions()},
    )
    
    # print(parser.get_format_instructions())
    # print(get_query(batch1, contract_questions))

    # url = "https://www.defense.gov/News/Contracts/Contract/Article/3716593/"
    # contract_text = scrape(url)

    # response = ""
    response = invoke_query(prompt, model, parser, model_batch)

    # Specify the file name
    csv_file = "gpt_comparison.csv"

    fieldnames = response['contracts'][0].keys()

    # Open the CSV file in write mode
    with open(csv_file, 'w', newline='') as file:
        # Create a CSV writer object
        writer = csv.DictWriter(file, fieldnames=fieldnames, delimiter='|')
        
        # Write the header
        writer.writeheader()
        
        # Write the data rows
        for contract in response['contracts']:
            writer.writerow({k: str(v).replace('"', '') for k, v in contract.items()})

    print(f"Response: {type(response)}")

